server:
  port: 6002

spring:
  profiles:
    active: dev # 多环境配置加载内容dev/prod,不写就是默认default配置

rocketmq:
  name-server: 10.189.140.61:9876
  producer:
    group: zhan-producer
    send-message-timeout: 30000
    retry-times-when-send-failed: 3
    retry-times-when-send-async-failed: 3
